### ISSUE TITLE
Empty self hosting template uses old Nancy version leading to Exception on Windows

### ISSUE THREAD

**Issue by philippgille** [NancyFx/Nancy.Templates#16]
### Problem

I created a new Project with VS 2013 Community with the template "Nancy Empty Application with self-hosting". I got an `AutomaticUrlReservationCreationFailureException`. [This wiki page](https://github.com/NancyFx/Nancy/wiki/Self-Hosting-Nancy) and other sources said you need to customize a `HostConfiguration ` for that. That's what I did:

```csharp
namespace NancySelfHosted
{
    using System;
    using Nancy.Hosting.Self;

    class Program
    {
        static void Main(string[] args)
        {
            var uri = new Uri("http://localhost:8080");

            HostConfiguration hostConfiguration = new HostConfiguration();
            hostConfiguration.UrlReservations.CreateAutomatically = true;

            using (var host = new NancyHost(hostConfiguration, uri))
            {
                host.Start();

                Console.WriteLine("Your application is running on " + uri);
                Console.WriteLine("Press any [Enter] to close the host.");
                Console.ReadLine();
            }
        }
    }
}
```

When launching the application I got the Windows prompt to execute the following command as Administrator:
`"C:\Windows\System32\netsh.exe" http add urlacl url=http://+:8080/ user=Everyone`

After confirming the dialog, I got this exception:
`InvalidOperationException: "Unable to configure namespace reservation"`
in `Nancy.Hosting.Self.NancyHost.StartListener()`
And googling for the message didn't show any helpful results.

### Solution

Somewhere else, also related to namespace reservations, I read that updating the dependencies helped. So I did that and afterwards it worked fine.

The Windows prompt now executed:
`"C:\Windows\System32\netsh.exe" http add urlacl url=http://+:8080/ user=Jeder`

"Jeder" is German for "Everyone", and my OS is set to German, so it seemed to be a language related problem.

### To do

The version numbers in the templates need to get updated.
I haven't worked with templates yet, so I don't know which files to edit to make everything work. That's why I created this issue. Maybe someone can help out?

**Comment by thecodejunkie** [comment]
Moving the discussion on this to #12
