### ISSUE TITLE
Unable to start new project using VS2012 Update 3

### ISSUE THREAD

**Issue by mjbates7** [NancyFx/Nancy.Templates#6]
I installed the nancy vs templates to VS2012 update 3 which appear fine under new project > web but when I select a template, I only get a "Name" box at the bottom of the dialog, I don't get an option to enter "Location" or "Solution Name"

![image](https://f.cloud.github.com/assets/4522738/909209/b178e7f0-fdb6-11e2-97dd-2393daea7dc3.png)

![image](https://f.cloud.github.com/assets/4522738/909215/d4c0bab2-fdb6-11e2-9b4d-59e4330909da.png)

When I click "OK" I get an error "Unable to locate the solution directory. Please ensure that the solution has been saved" and none of the DLLs are installed to the application as it gives not referenced errors.

Screenshot of the open solution showing the missing assemblies:
![image](https://f.cloud.github.com/assets/4522738/909205/8dc78eec-fdb6-11e2-8223-fc4e19349be8.png)

**Comment by thecodejunkie** [comment]
All these templates will be replaced by Dotnet CLI compatible templates
